
<p style="padding: 40px"></p>
<div class="footer">
  <footer>
  <p>Brought to you by Erika, Janika, Jo, Kim and Rosie</p>
  <p>Copyright &copy; CSS3_photo_dark | <a href="http://www.css3templates.co.uk">design from css3templates.co.uk</a></p>
</footer>
</div>

<script type="text/javascript">
if ( window.addEventListener ) {
  var state = 0, konami = [38,38,40,40,37,39,37,39,66,65];
  window.addEventListener("keydown", function(e) {
    if ( e.keyCode == konami[state] ) state++;
    else state = 0;
    if ( state == 10 )
      window.location = "/thanks.php";  //you can write your own code here
    }, true);
}
</script>

</body>

</html>
