
        <div id="site_content">
            <div class="content">
                <h1>Examples</h1>
                <p>This page contains examples of all the styled elements available as part of this design. Use this page for reference, whilst you build your website.</p>
                <h2>Headings</h2>
                <p>These are the different heading formats:</p>
                <h1>Heading 1</h1>
                <h2>Heading 2</h2>
                <h3>Heading 3</h3>
                <h4>Heading 4</h4>
                <h5>Heading 5</h5>
                <h6>Heading 6</h6>
                <h2>Text</h2>
                <p>The following examples show how the text (within '&lt;p&gt;&lt;/p&gt;' tags) will appear:</p>
                <p><strong>This is an example of bold text</strong></p>
                <p><i>This is an example of italic text</i></p>
                <p><a href="#">This is a hyperlink</a></p>
                <h2>Tables</h2>
                <p>Tables should be used to display data and not used for laying out your website:</p>
                <table style="width:100%; border-spacing:0;">
                    <tr>
                        <th>Item</th>
                        <th>Description</th>
                    </tr>
                    <tr>
                        <td>Item 1</td>
                        <td>Description of Item 1</td>
                    </tr>
                    <tr>
                        <td>Item 2</td>
                        <td>Description of Item 2</td>
                    </tr>
                    <tr>
                        <td>Item 3</td>
                        <td>Description of Item 3</td>
                    </tr>
                    <tr>
                        <td>Item 4</td>
                        <td>Description of Item 4</td>
                    </tr>
                </table>
                <h2>Form Elements</h2>
                <form action="#" method="post">
                    <div class="form_settings">
                        <div class="input-wrapper"><label for="field1">Form field example</label><input type="text" name="field1" id="field1" value="" /></div>

                        <div class="input-wrapper"><label for="field2">Textarea example</label><textarea rows="8" cols="50" name="field2" id="field2"></textarea>
                        </div>

                        <div class="input-wrapper"><label for="field3">Checkbox example</label><input class="checkbox" type="checkbox" name="field3" id="field3" value="" /></div>
                        <div class="input-wrapper"><label for="field4">Dropdown list example</label><select id="field4" name="field4"><option value="1">Example 1</option><option value="2">Example 2</option></select></div>
                        <p style="padding-top: 15px"><label>&nbsp;</label><input class="submit" type="submit" name="name" value="button" /></p><br />
                    </div>
                </form>
            </div>
