
<form action="/login.php" method="post">
    <div class="form_settings">
        <div class="input-wrapper"><label for="username">Username</label><input type="text" name="username" id="username" /></div>
        <div class="input-wrapper"><label for="password">Password</label><input type="password" name="password" id="password" /></div>
        <p style="padding-top: 15px; padding-bottom: 100px"><label>&nbsp;</label><input class="submit" type="submit" name="button" value="login" /></p><br />
    </div>
</form>
