<!DOCTYPE HTML>
<html>

<head>

    <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
    <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
    <script>tinymce.init({ selector:'textarea' });</script>
    <title>creepycourgetti</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="og:description" content="Who doesn't like a good scary story? Not us -- we love them. Take your pick of a cornucopia of creepy right here.">
    <meta name="description" content="Who doesn't like a good scary story? Not us -- we love them. Take your pick of a cornucopia of creepy right here.">
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <link rel="stylesheet" type="text/css" href="css/style.css" />
</head>

<body>
    <div id="main">
        <header>
            <div id="logo">
                <div id="logo_text">
                    <!-- class="logo_colour", allows you to change the colour of the text -->
                    <h1><a href="/index.php">creepy<span class="logo_colour">courgetti</span></a></h1>
                    <p>low-carb scares to bloat you with fear</p>
                </div>
            </div>

            <nav>
                <ul class="sf-menu" id="navtop">
                <?php foreach (ARTICLE_CATEGORIES as $id => $category) :?>
                    <li><a href="index.php?category=<?= $id; ?>"><?= $category; ?></a>
                <?php endforeach; ?></a></li>
              </ul>
              <p>&nbsp;</p>
                <ul class="sf-menu" id="navbottom">
                  <li><a href="index.php">home</a></li>
                        <li><a href="about.php">about us</a></li>
                        <li><a href="search.php">search</a></li>
                        <?php if (!empty($_SESSION[USER_SESSION])): ?>
                              <li><a href="post.php">post</a></li>
                              <li><a href="admin.php">admin</a></li>
                              <li><a href="login.php?logout=true">logout</a></li>
                            <?php else: ?>
                              <li><a href="login.php">login</a></li>
                            <?php endif; ?>
               </ul>
            </nav>

            <script type="text/javascript">
                $( document ).ready(function() {
                  var strValue = window.location.pathname.match(/[^\/]+$/)[0] + location.search;
                  $('a[href="'+strValue+'"]').addClass('selected');
                });
            </script>
        </header>
</header>

<div id="site_content">
    <div class="content">
