
            <div id="site_content">
                <div class="content">
                    <h1>We are the ladies of GiT 4</h1>
                    <h2>... and these are our stories</h2>
                    <table style="width:100%; border-spacing:0;">
                        <tr>
                            <td class="gitname">Erika Braverman</td>
                            <td>Description of Item 1</td>
                        </tr>
                        <tr>
                            <td class="gitname">Janika Chitrasena</td>
                            <td>Description of Item 2</td>
                        </tr>
                        <tr>
                            <td class="gitname">Jo Noble-Smith</td>
                            <td>Description of Item 3</td>
                        </tr>
                        <tr>
                            <td class="gitname">Kim Lofthouse</td>
                            <td>Description of Item 4</td>
                        </tr>
                        <tr>
                            <td class="gitname">Rosie Earnshaw</td>
                            <td>Description of Item 4</td>
                        </tr>
                    </table>
                </div>
              </div>
