
            <div id="site_content">
                <div class="content">
                    <h1>We are the ladies of GiT 4</h1>
                    <h2>and these are our stories</h2>
                    <table style="width:100%; border-spacing:0;">
                      <col width="180">
                      <col width="420">
                        <tr>
                            <td class="gitname">Erika Braverman</td>
                            <td class="gitdesc">Scrum Master, native Chicagoan, wife, mom of two, perpetual worrier. Wanted to take this course so I have a better understanding of what my teams do and so one day I can teach my kids how to code.</td>
                        </tr>
                        <tr>
                            <td class="gitname">Jo Noble-Smith</td>
                            <td class="gitdesc">Aviation Technology Graduate, Flight Simulator Engineer, Occasional Pilot. Interested in OOP, JavaScript, Python, C++.</td>
                        </tr>
                        <tr>
                            <td class="gitname">Kim Lofthouse</td>
                            <td class="gitdesc">Humanities graduate, office admin/project management ninja, dev in training and opinionated optimist. Interested in: scrum, kanban, backend development, bridging the gap between traditional STEM and non-STEM mindsets.</td>
                        </tr>
                        <tr>
                            <td class="gitname">Rosie Earnshaw</td>
                            <td class="gitdesc">Description of Item 4</td>
                        </tr>
                    </table>
                </div>
              </div>
