

<h1>Articles</h1>
	<ul>
		<?php foreach ($vars['articles'] as $article): ?>
		<li> <?= $article['title']; ?>
			[ <a href="edit.php?id=<?= $article['id']; ?>">edit</a> |
			<a href="admin.php?action=delarticle&id=<?= $article['id']; ?>">delete</a> ]
		</li>
	<?php endforeach; ?>
	</ul>


<h1>Users</h1>
<ul>
	<?php foreach ($vars['users'] as $user): ?>
		<li><?= $user['username']; ?> (<?= USER_ROLES[$user['role']]; ?>) [<a href="admin.php?action=deluser&id=<?= $user['id']; ?>">delete</a>]</li>
	<?php endforeach; ?>

</ul>
