
        <?php foreach ($vars['articles'] as $article): ?>
          <div class="list-item">
            <h2 class="list-post-title">
              <a href="article.php?id=<?= $article['id'];?>"><?= $article['title'];?></a>
            </h2>
            <div class="list-post-date">
              <time><?= date('d M Y'); ?></time> by <?= $article['fullname']; ?>
          

            </div>
          </div>
        <?php endforeach; ?>
