	<p style="padding: 20px"></p>
	<form action="post.php" method="post" style="width: 100%">
		<div class="form_settings">
		<div class="input-wrapper"><label for="title">Title </label><input name="title" type="text"/></div>

	<div class="input-wrapper"><label for="title">Category </label>
		<select name="category">
			<?php foreach (ARTICLE_CATEGORIES as $id => $category): ?>
				<option value="<?= $id; ?>"><?= $category; ?></option>
			<?php endforeach; ?>
		</select>
	</div>

<div class="input-wrapper"><label for="body">Article </label>
	<textarea name="body" col="50" rows="20" style="width: 100%"></textarea>
	</div>
<p style="padding-top: 15px; padding-bottom: 10px; width: 100%"><input class="submit" type="submit" value="Post" /></p><br />
</form>
