
<h1>Sign up to creepycourgetti</h1>

<form action="admin.php?action=newuser" method="post">
	<div class="form_settings">
		<div class="input-wrapper">
			<label for="username">Username</label>
			<input type="text" name="username" id="username" />
		</div>
	</div>
	<div class="form_settings">
		<div class="input-wrapper">
			<label for="fullname">Full Name</label>
			<input type="text" name="fullname" id="fullname" />
		</div>
	</div>
	<div class="form_settings">
		<div class="input-wrapper">
			<label for="email">Email</label>
			<input type="text" name="email" id="email" />
		</div>
	</div>
	<div class="form_settings">
		<div class="input-wrapper">
			<label for="password">Password</label>
			<input type="password" name="password" id="password" />
		</div>
	</div>

	<p style="padding-top: 15px; padding-bottom: 10px">
		<label>&nbsp;</label>
		<input class="submit" type="submit" name="button" value="New User" />
	</p>
	<br />
</form>
