<!DOCTYPE HTML>
<html>
<head>
<title>Search Box</title>

</head>
<body>
	<!-- HTML for SEARCH BAR -->
<form action="" method="POST">
<input type ="text" name="search" placeholder="Search..." value='<?echo isset($_POST['search']) ? ($_POST['search']): ""?>'>
<div id="Searchresults"></div>
</form>

<?if(isset($vars['results'])){
  $find_page=$vars['results'];
  while($row = $find_page->fetch(PDO::FETCH_ASSOC))
 {
   echo "Search results:" ."<a href='article.php?id=".$row['id']."'>".$row['title']."</a><br />";
 }
   $count = $find_page->rowCount();
   echo "Search results found:" . $count . "<br />";
}?>

</body>
</html>
